version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: justice-hub-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=justice_hub_develop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: