spring.application.name=Justice Hub API

spring.datasource.url=jdbc:postgresql://localhost:5432/justice_hub_develop
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml